version: '3'
services:
  react-front: 
    image: react-front
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - inside
    ports:
      - "3000:3000"
  fastapi:
    image: fastapi-back
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - inside
networks:
  inside: