# install dependencies of front
FROM node:21-alpine as node_modules
WORKDIR /app
COPY ./src/frontend/package.json ./src/frontend/package-lock.json ./
RUN npm install
COPY ./src/frontend ./
RUN npm run build 
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
